#! /bin/bash
# chkconfig: - 85 15
PATH=/usr/local/nginx
DESC="nginx daemon"
NAME=nginx
DAEMON=$PATH/sbin/$NAME
CONFIGFILE=$PATH/conf/$NAME.conf
PIDFILE=$PATH/logs/$NAME.pid
scriptNAME=/etc/init.d/$NAME

set -e
[ -x "$DAEMON" ] || exit 0

do_start() {
    $DAEMON -c $CONFIGFILE || echo -n "nginx is already running"
}

do_stop() {
    $DAEMON -s stop || echo -n "nginx is not running"
}

do_reload() {
    $DAEMON -s reload || echo -n "nginx can't reload"
}

do_status() {
    if [ -r "$PIDFILE" ]; then
        echo -n "$DESC was already running"
    else
        echo -n "$NAME is not started yet"
    fi
}

case "$1" in
start)
    echo -n "Starting $DESC: $NAME"
    do_start
    echo "."
    ;;
stop)
    echo -n "Stopping $DESC: $NAME"
    do_stop
    echo "."
    ;;
reload|graceful)
    echo -n "Reloading $DESC configuration..."
    do_reload
    echo "."
    ;;
restart)
    echo -n "Restarting $DESC: $NAME"
    do_stop
    do_start
    echo "."
    ;;
status)
    do_status
    echo "."
    ;;
*)
    echo "Usage: $scriptNAME {start|stop|reload|restart}" >&2
    exit 3
    ;;
esac
exit 0
